server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tensquare_base?characterEncoding=utf-8&&useSSL=false
    username: root
    password: 123456

  jpa:
    database: mysql
    show-sql: true
    open-in-view: false
  rabbitmq:
    host: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true   #模块之间可以跨域访问
ip: 127.0.0.1